Allophone State Fsa bug for arc's weight leaving silence
rwth-i6/rasr pull request #14
Opened 2022-04-13 11:17 UTC by Marvin84

Given a static allophone Finite State Acceptor (FSA), the `ClassicTransducerBuilder`, applies the transition penalties on the arcs. The Fsa at this level makes use of Epsilon arcs in order to distinguish between different word ends, including silence. In the current implementation, any arc coming after Epsilon arc will have speech forward penalty. This means that after trimming the Epsilon arcs, the transition penalty for leaving silence and final speech state is always the respective exit penalties plus speech forward. This should be corrected in the `doExit()` function in order to subtract the speech forward and add the silence forward, when leaving silence.

2022-04-13 12:20 UTC, curufinwe commented
We don't use this much anymore, but does this code also work with skip connections? What if we have state-repetition set to 2 (because you work with phon0 here, but there is also phon1)?

2022-04-13 12:35 UTC, Marvin84 commented
>

2022-04-13 12:39 UTC, Marvin84 commented
> What if we have state-repetition set to 2 (because you work with phon0 here, but there is also phon1)?
As far as I see here, this is a transition-specific state type, and is not about the distinction between different state labels but just speech and silence. There is actually no use of `phone1` in any part of the code. However, for a cleaner solution, I will just use the `current.weights` which should have the correct state type.

2022-04-13 12:58 UTC, Marvin84 commented
> but does this code also work with skip connections?

Good point, this should be also corrected for the skip, where we have a similar problem. I will do the changes.

2022-04-13 13:11 UTC, albertz commented
Should we introduce an option to enable the new fixed behavior? I assume people who upgrade RASR would not expect that the behavior suddenly is different from before.

In RETURNN, we introduced the "behavior version" (https://github.com/rwth-i6/returnn/issues/508) such that the default settings can be reasonable when people use a recent behavior version while not breaking any older setup which uses an older behavior version. I think RASR doesn't have such a concept yet. Not sure if we want to introduce it (but this should maybe be a separate discussion).

In any case, I think the behavior should not just suddenly change, even if the old behavior was somehow wrong. For other things we also have always introduced options (@Marvin84 remember the other options regarding FSA stuff).

2022-04-13 13:18 UTC, Marvin84 commented
> the behavior should not just suddenly change

Here, in my opinion, we are not dealing with a behavior change due to the introduction of a new feature or functionality, but with a pure algorithmic bug. Surely, everybody should be notified about this, but continuing to use the 'old behavior' means applying a transition model that is incorrect.

2022-04-13 13:22 UTC, albertz commented
> ... but continuing to use the 'old behavior' means applying a transition model that is incorrect.

Yes. But we also have this case for some of the other options I introduced before.

"incorrect" is maybe also a strong word. Maybe "unexpected" is better. Because it "worked" already before (since many years).

People who would update RASR now suddenly might even get worse results when they don't check and maybe adapt the config?

2022-04-13 13:24 UTC, Marvin84 commented
> "incorrect" is maybe also a strong word. Maybe "unexpected" is better.

leaving silence state with probability of speech forward is not unexpected is just incorrect

2022-04-13 13:25 UTC, Marvin84 commented
> People who would update RASR now suddenly might even get worse results when they don't check and maybe adapt the config?

Yes, this should be tested. But this is independent of fixing the bug.

2022-04-13 13:28 UTC, albertz commented
> > People who would update RASR now suddenly might even get worse results when they don't check and maybe adapt the config?
> 
> Yes, this should be tested. But this is independent of fixing the bug.

Well, I personally would not introduce some new changed behavior (even when the old behavior was "wrong") without having an explicit option to enable the new behavior.

At least in RETURNN, we are very strict about never breaking old setups or changing the behavior of old setups. I think this is a good policy in general, also for RASR. But maybe @curufinwe, @michelwi, or also @ZhouW321 have different opinions on this? @JackTemaki maybe?

2022-04-13 13:30 UTC, albertz commented on src/Am/TransitionModel.cc
> +            //we need to correct for the algorithmic bug introduced by epsilon arcs in case of exit,
The comment-style is inconsistent to the remaining comment-style in this file. I think there should be a space after `//`.

2022-04-13 13:37 UTC, albertz commented on src/Am/TransitionModel.cc
> +            correctedWeight = t_->semiring()->extend(correctedTdp, Fsa::Weight((*transitionModel_[silType])[StateTransitionModel::forward]));
I wonder if this is the best place to have this. (It's long ago that I worked with this code so I don't really remember anymore.) For example, can't we directly do this when we introduce the eps arcs? It's sounds a bit like we need this here as a workaround for another bug.

2022-04-13 13:42 UTC, Marvin84 commented on src/Am/TransitionModel.cc
> +            correctedWeight = t_->semiring()->extend(correctedTdp, Fsa::Weight((*transitionModel_[silType])[StateTransitionModel::forward]));
Yes, this solution is kinf od hacky, because it corrects for this specific algorithmic solution and this specific fsa.
The clean solution would be to extend the `State` struct to have also the information about the emission label of the previous arc. But this would be even a bigger change and would actually need probably a separate module.

2022-04-13 13:53 UTC, Marvin84 commented on src/Am/TransitionModel.cc
> +            correctedWeight = t_->semiring()->extend(correctedTdp, Fsa::Weight((*transitionModel_[silType])[StateTransitionModel::forward]));
> because you work with phon0 here

I just saw that the `statetype(Fsa::LabelId emission)` function here in this class also distinguishes only between silence and `phone0`.

2022-04-17 10:46 UTC, Marvin84 commented
Hi everybody, 
Following @albertz 's suggestion I am proposing a less hacky version, where a proper fsa implementation with context is provided. Furthermore, I introduced a flag that will decide between the default and the new behavior.
Looking forwrad to your suggestions.

2022-05-27 12:36 UTC, JackTemaki commented
In my opinion, as we were previously not using this particular version of RASR in experiments, I think it is fine to directly make the new behavior the default.

2022-05-27 13:02 UTC, albertz commented
> In my opinion, as we were previously not using this particular version of RASR in experiments, I think it is fine to directly make the new behavior the default.

I don't understand this argument. We would expect that all versions of RASR behave the same, or not? Otherwise it complicates everything to switch over to another RASR versions.

2022-05-27 13:48 UTC, JackTemaki commented
> > In my opinion, as we were previously not using this particular version of RASR in experiments, I think it is fine to directly make the new behavior the default.
> 
> I don't understand this argument. We would expect that all versions of RASR behave the same, or not? Otherwise it complicates everything to switch over to another RASR versions.

I do not consider them behaving the same. It only complicates anything it if this affects not only full-sum training. Because in that case we anyway have multiple different versions of RASR. Also changes to RASR are very rare (the last algorithmic change was more than one year ago), So we could even just start (or rather continue) giving version numbers for RASR itself.

2022-05-27 15:50 UTC, Marvin84 commented
I already changed the first implementation proposed in the original pull request with the option of having a flag that selects new or old behavior. I would appreciate if you could give feedback on the specific implementation. @curufinwe @JackTemaki

2022-05-27 16:51 UTC, JackTemaki commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
What I meant in my comments is changing this to true.

2022-05-27 19:26 UTC, albertz commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
I very much disagree here. I think there should never be behavior changes between RASR versions. Users should be able to switch or update RASR versions without being afraid that this would break their setup.

I have no idea how you get to this idea that it should be the other way around.

2022-05-28 02:34 UTC, Marvin84 commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
I think I already mentioned that the old behavior is incorrect on the theoretical level. We already tested the new code and in practice we get the same WER. I am fine with having this parameter false, but it should be clear that the default behavior does not correspond to a proper transition model when leaving silence states.

2022-05-30 15:22 UTC, JackTemaki commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
> I have no idea how you get to this idea that it should be the other way around

Again, I am stating in my opinion we should (in this specific case) change this flag to default `True` as:
 - It does not affect our regular hybrid training (if it does in a relevant manner, then surely it should be False)
 - It is (as Tina said) definitely a wrong implementation, not only a different, so I would consider this a bug-fix and not a behavioural change.
 - I do not know of anyone using the Github master branch of RASR in experiments, and we are currently in the process of making the master usable for i6, so I would want the correct behavior as default when I switch.
 - We have multiple incompatible RASR versions, and the master branch here will be the one where we try to unify at least some parts of them.

2022-05-30 15:31 UTC, albertz commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
> It does not affect our regular hybrid training

I thought it does affect realignments, full-sum training, and maybe also search?

> It is (as Tina said) definitely a wrong implementation, not only a different, so I would consider this a bug-fix and not a behavioural change.

A change in behavior is a change in behavior.

> I do not know of anyone using the Github master branch of RASR in experiments, and we are currently in the process of making the master usable for i6, so I would want the correct behavior as default when I switch.

I don't understand. I would want that when I switch RASR versions that my setups behave as before, even if it was incorrect before.

> We have multiple incompatible RASR versions, and the master branch here will be the one where we try to unify at least some parts of them.

Yes, and this makes it even more important that people can just switch to the master branch and don't have to expect that their setups will suddenly work differently.

But anyway, I think this is a decision for @curufinwe.

In RETURNN, we definitely also handle it like that, that even if there are bugs, we introduce a new behavior version, such that people can always safely stay on master branch.

2022-06-08 09:23 UTC, curufinwe requested changes

2022-06-08 09:23 UTC, curufinwe commented on src/Am/TransitionModel.cc
> +class TransitionModel::ApplicatorWithContext {
There is a lot of duplication of code in this class. Please refactor this into a common base class and have Applicator and ApplicatorWithContext inherit from it.

2022-06-08 09:23 UTC, curufinwe commented on src/Am/TransitionModel.hh
> +    Fsa::ConstAutomatonRef applyWithContext(
Add documentation describing how this function is different from apply.

2022-06-08 09:45 UTC, JackTemaki commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
I know that the default batch-norm settings are far from "correct" in the sense of what you would expect, and this was fixed with a new "behavior" version, but I don't know of anything else.

2022-06-08 13:02 UTC, Marvin84 commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
I took a quick look at the link above. In my opinion, these are all real behavior changes. Also the case of batch normalization it seems to me that this is more of a different implementation choice, involving hyperparameters and aspects regarding complexity optimization. How is this comparable with our example here where we have a conceptually wrong modeling approach, i.e. we have an automaton that has the probability of leaving silence equal to the probability of leaving speech plus exiting silence.

2022-06-08 13:09 UTC, albertz commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
It's exactly the same. In all cases, the behavior was wrong before and is now correct. E.g. the batch norm settings before were really totally wrong, conceptually wrong, did not make any sense. The other examples are all similar.

You could also call this option you introduce here just a hyper param.

2022-06-08 13:15 UTC, Marvin84 commented on src/Am/ClassicTransducerBuilder.cc
> +        false);
I see it differently. But I think there is no point in continuing this discussion. The real issue we need to discuss is whether in rasr we can consider similar behavior-monitoring as in returnn. And this should solve the issue.

2022-06-15 09:33 UTC, curufinwe commented on src/Am/TransitionModel.cc
> +class TransitionModel::ApplicatorWithContext {
Yes

2022-11-21 18:09 UTC, Marvin84 commented
With the help of @curufinwe the architecture refactoring following the implemented logic is carried out.
@SimBe195 @JackTemaki @curufinwe the current code has been already tested. Please add your review.

2022-11-28 17:06 UTC, SimBe195 requested changes

2022-11-28 17:06 UTC, SimBe195 commented on src/Am/TransitionModel.cc
> +            ap.reset(new ApplicatorWithContext(*this));
I don't really like that the `ApplicatorType`s refer to classes which are named differently and have names which themselves sound like subclasses of `AbstractApplicator`. I would perhaps somewhat unify the naming scheme like this:

- `StandardApplicator` -> `LegacyApplicator`
- `LegacyBuggyApplicator` -> `Legacy` or `LegacyType`
- `"legacy-buggy"` -> `"legacy"`
- `ApplicatorWithContext` -> `CorrectedApplicator`
- `CorrectedApplicator` -> `Corrected` or `CorrectedType`

That way it's clearer which ones belong together.

2022-11-29 10:45 UTC, curufinwe requested changes

2022-11-29 18:08 UTC, curufinwe commented on src/Am/TransitionModel.hh
> +    enum TyingType {
These are not scoped enums. Scoped enums are defined by adding either the `class` or `struct` keyword after the `enum` keyword. This is why you could not name the enum values LegacyApplicator and CorrectedApplicator as in an unscoped enum these names are added to the surrounding namespace which already contains these names for the classes.

2022-11-30 18:24 UTC, Marvin84 commented on src/Am/TransitionModel.hh
> +    enum TyingType {
Could we please open another pull request for this? This does not have any effect on the config side and can be fixed later.

2022-11-30 18:46 UTC, Marvin84 commented
@curufinwe and @SimBe195 I reversed for now to the classic enum. I will then open another pull request for this to have a consistent solution for all enums under `TransitionModel`. Could you please merge now?

2022-12-01 07:53 UTC, SimBe195 approved these changes

2022-12-02 00:40 UTC, curufinwe approved these changes

2022-12-02 00:42 UTC, merged