Add initial version of new documentation (still incomplete)
rwth-i6/rasr pull request #22
Opened 2022-06-08 09:30 UTC by curufinwe

Copy a lot of content from the RASR wiki into a sphinx documentation distributed with the source code. Doxygen file is also moved into new doc folder. Documentation can be created by calling "make html" in the doc folder.

2022-06-08 14:38 UTC, JackTemaki requested changes
First of all, thanks a lot for adding a sphinx documentation to RASR, just by quickly reviewing it I already learned new things I did not know :sweat_smile:  

Regarding the general structure, the only page I do not like that much is the "Architecture" page, as this is first not what I would have expected under architecture, but also because it is a single large page. But this is certainly something we can move around later, maybe separating this into a "Structure" and "Compiling/Installation" section or so.

So my change request is mostly about the File Format Specification tables, because this is not displayed correctly for me.

2022-06-08 14:38 UTC, JackTemaki commented on doc/file_formats/bliss_corpus.rst
> +        | ``audio`` (required) name of the corresponding audio file. The attribute value is first resolved using the configuration of the corpus description object.
This is not really visible in the final webpage, as the site width is limited and this goes out of bounds in the table. The same happens for the bliss lexicon. Here we need to find some solution.

2022-06-08 14:38 UTC, JackTemaki commented on doc/file_formats/lattice.rst
> +=== References ===
```suggestion
References
----------
```

2022-06-15 09:30 UTC, curufinwe commented on doc/file_formats/bliss_corpus.rst
> +        | ``audio`` (required) name of the corresponding audio file. The attribute value is first resolved using the configuration of the corpus description object.
We could make this just a sequence of elements without the table structure. Would that be OK for you?

2022-07-19 12:09 UTC, michelwi commented on doc/architecture.rst
> +Note that there is also the Tensorflow module which provides an own FeatureScorer.
Fix Denglish
```suggestion
Note that there is also the Tensorflow module which provides a separate FeatureScorer.
```

2022-07-19 12:10 UTC, michelwi commented on doc/architecture.rst
> +Please note that for the streaming recognizer, the set of dependencies is larger (gRPC, Protobuf, Boost, streaming API, OPUS resampling library).
Information refer to AppTek IP. Streaming recognizer is not part of the github rasr version

2022-07-19 12:16 UTC, michelwi commented on doc/architecture.rst
> +The alignment is a frame-level mapping from feature vector index within a segment (no time stamps are stored here, just integer indices 0, 1, 2, ... relative to segment start) to a triphone HMM state
> the first 26 bits of the allphone state id are used for the allophone index; the latter 6 bits for the state.

I think the most significant bits store the state id and the least significant bits the allophone index.

2022-07-19 12:22 UTC, michelwi commented on doc/architecture.rst
> +Channel
duplicate information with channel.rst

2022-07-22 18:00 UTC, curufinwe commented on doc/architecture.rst
> +Build environment
But let's do it in a separate PR :grinning:

2022-07-22 18:00 UTC, curufinwe commented on doc/architecture.rst
> +The emission labels, i.e. the labels
I would leave it in anyway. Many people never open the source code to read the documentation in there.

2022-07-25 07:45 UTC, michelwi commented on doc/architecture.rst
> +The alignment is a frame-level mapping from feature vector index within a segment (no time stamps are stored here, just integer indices 0, 1, 2, ... relative to segment start) to a triphone HMM state
My comment was not referring to the nomenclature "first n bits" vs "most significant bits" etc, but because I think there is a factual error here:
The text now states that the _least_ significant bits store the state whereas I have in mind that the state is stored in the _most_ significant bits.

Can you please verify/clarify that the text is correct and my recollection is wrong?

2022-07-25 15:24 UTC, curufinwe commented on doc/architecture.rst
> +The alignment is a frame-level mapping from feature vector index within a segment (no time stamps are stored here, just integer indices 0, 1, 2, ... relative to segment start) to a triphone HMM state
According to rasr_cache.py your memory is correct. I have updated the documentation.

2022-07-26 10:31 UTC, michelwi approved these changes

2022-07-26 12:04 UTC, merged