fullsum training automaton: RNA/CTC/HMM topology
rwth-i6/rasr pull request #24
Opened 2022-06-10 14:41 UTC by ZhouW321

sprint automaton based  from-scratch full-sum training using BW Loss

2022-06-10 15:24 UTC, Marvin84 commented on src/Nn/AllophoneStateFsaExporter.cc
> +// Note: pronunciation variants ignored here, i.e. no normalization
Do I get it right that here you overwrite the arc weights with only transition scores?
If yes, you are ignoring both lemma level and lexicon level pronunciation normalizations. This makes the implementation not generic enough.
And the question is: why do you even need to have the HMM topology modified here? We already have an FSA builder module `ClassicTransducerBuilder` that prepares the FSA for full-sum with our standard HMM topology that supports both mono-state and 3-partite. Shouldn't you extend that?

2022-08-17 09:12 UTC, SimBe195 requested changes

2022-08-17 09:12 UTC, SimBe195 commented on src/Nn/AllophoneStateFsaExporter.cc
> +            stateDepth[sId] = 0;
Why do we need to iterate over the arcs if the state is final? Shouldn't the for loop be only in the "else" case of `if (state->isFinal() )`

2022-08-17 09:12 UTC, SimBe195 commented on src/Nn/AllophoneStateFsaExporter.cc
> +            --expand; // reduce expansion
I would say it's unexpected behavior that the minimum duration may be reduced automatically. In my opinion the user should receive a warning when that happens.

2022-11-22 12:47 UTC, ZhouW321 commented
no need anymore

2022-11-22 12:47 UTC, closed without merging