flexible alignment: auto-subsample, peaky, as-is, etc.
rwth-i6/rasr pull request #25
Opened 2022-06-10 17:56 UTC by ZhouW321

also improve code logic of AligningFeatureExtractor

2022-06-14 14:37 UTC, SimBe195 commented
I think a lot of this code could be refactored by implementing these operations (subsample, convert to single state, make peaky) as flow-nodes instead. This would perhaps be more elegant from a design perspective and also give the user more control.

2022-06-14 15:48 UTC, ZhouW321 commented
theoretically yes. This has to be done before alignment is input to the Extractor/Processor. Then it would require one/several flow nodes with the same full capability as the Extractor/Processor w.r.t. AM, allophone and state-tying, etc., to parse and modify the alignment. This will be basically copying the same code/members of Extractor/Processor to that flow node class and copy over the same modify function (subsample, make peaky, etc.) there as well. And it requires the users to additionally setup the flow files instead of just one config parameters, which IMO would even increase difficulty and need additional effort to setup workflow manager, e.g. sisyphus.

2022-06-14 16:32 UTC, SimBe195 commented
Ah, that's true, state-tying has to be applied before. Yeah, that would make it way too complicated.

2022-08-17 09:40 UTC, SimBe195 requested changes

2022-08-17 09:40 UTC, SimBe195 commented on src/Nn/BufferedAlignedFeatureProcessor.cc
>      for (u32 i = 0; i < batchSize; i++) {
Variable names `i` and `idx` next to each other are not so nice.

2022-08-17 09:40 UTC, SimBe195 commented on src/Nn/BufferedAlignedFeatureProcessor.cc
> +                //}
Commented code can be removed?

2022-08-17 09:40 UTC, SimBe195 commented on src/Speech/AligningFeatureExtractor.cc
> +        makeSingleStateAlignment(&alignmentRef_->data());
How "peaky-alignment" and "force-single-state" play together is not obvious without looking at the code. At the moment "peaky-alignment" overwrites "force-single-state" in that it always also reduces the alignment to single-state regardless of the value of `forceSingleState_`. I think it would be clearer if "peaky-alignment" reduces the alignment to single-state if and only if "force-single-state" is set to true, then they would have their independent effects. This would also allow using peakiness for 3-state alignments in an obvious way. The `makePeakyAlignment` function can be easily extended to preserve the states, so I would change it to a template function like
`template <bool forceSingleState> void AligningFeatureExtractor::makePeakyAlignment` and then change this case distinction to
```suggestion
    if ( peakyAlignment_ ) {
        if ( forceSingleState_ )
            makePeakyAlignment<true>(&alignmentRef_->date());
        else
            makePeakyAlignment<false>(&alignmentRef_->data());
    } else if ( forceSingleState_ )
        makeSingleStateAlignment(&alignmentRef_->data());
```

2022-11-22 12:44 UTC, ZhouW321 commented on src/Speech/AligningFeatureExtractor.cc
> +        makeSingleStateAlignment(&alignmentRef_->data());
yes, peaky alignment is not necessarily single state and these can be separated.  As  forceSingleState_ is a data member already and there's not much overhead with the for loop over alignments, a template function is not necessary here.

2022-11-22 12:48 UTC, ZhouW321 commented
no need anymore

2022-11-22 12:48 UTC, closed without merging