Dense tying for mono/di/tri-phone with end of word classes
rwth-i6/rasr pull request #38
Opened 2022-11-17 14:02 UTC by Marvin84

This completes different dense tyings and adds the possibility of using the end of word classes for the dense tying. This type of tying is used mostly for the factored hybrid model.

1. I corrected the already implemented `DiphoneNoTyingDense` name into `DiphoneDense`. I assume that the whole set of triphone state classes is equivalent to no tying, as soon as we reduce the context to first or zero order, for diphone and monophone, respectively, it might be better to avoid appending `Notying` for better understandability.
2. `MonophoneDense` tying has two additional labels for silence, and three additional labels corresponding to `#` which are effectively never used. This is important since keeps the mapping consistent when one switches to a higher phonetic order.

2022-11-22 10:30 UTC, SimBe195 requested changes

2022-11-22 10:30 UTC, SimBe195 commented on src/Am/ClassicStateTying.cc
> +                                                                     "wether boundary classes should be considered during state-tying",
There is a typo in "whether". Maybe you can fix this while you're at it.

2022-11-22 10:30 UTC, SimBe195 commented on src/Am/ClassicStateTying.cc
> +                        (a.allophone()->boundary != Am::Allophone::isFinalPhone));
Can't this be simplified to just
`u32 weClass = a.allophone()->boundary & Am::Allophone::isFinalPhone;`?

2022-11-22 10:36 UTC, SimBe195 commented on src/Am/ClassicStateTying.cc
> +MonophoneDense::MonophoneNoStateTyingDense(const Core::Configuration& config, ClassicStateModelRef stateModel)
This should be `MonophoneDense::MonophoneDense`.

2022-11-22 10:37 UTC, SimBe195 commented on src/Am/ClassicStateTying.cc
> +                                                                    false);
This parameter is still missing in the header file.

2022-11-22 11:19 UTC, Marvin84 commented on src/Am/ClassicAcousticModel.cc
> +        "diphone-dense", diphoneDense,
We had just one HiWi using this and he did not publish any recipe, no official setup is going to break.

2022-11-22 13:37 UTC, Marvin84 commented on src/Am/ClassicStateTying.cc
> +                        (a.allophone()->boundary != Am::Allophone::isFinalPhone));
I do not understand your proposed solution. An allophone can have different boundary classes and the second argument is one possible class (btw, with a value equal to 2), how would this decide whether you have an allophone of word end class or not?

2022-11-22 13:53 UTC, SimBe195 commented on src/Am/ClassicStateTying.cc
> +                        (a.allophone()->boundary != Am::Allophone::isFinalPhone));
As I understand, the boundary is represented as a bit-mask. The 4 options are:
`"" = 00b = 0 = isWIthinPhone`
`"@i" = 01b = 1 = isInitialPhone`
`"@f" = 10b = 2 = isFinalPhone`
`"@i@f" = 11b = 3 = isInitialPhone | isFinalPhone"`
So using bit-wise 'and' with `isFinalPhone` you can find out if the boundary is an EOW class, i. e. option 2 or 3.

2022-11-22 13:59 UTC, Marvin84 commented on src/Am/ClassicStateTying.cc
> +                        (a.allophone()->boundary != Am::Allophone::isFinalPhone));
But this does not give me 0 or 1 as result

2022-11-22 14:04 UTC, SimBe195 commented on src/Am/ClassicStateTying.cc
> +                        (a.allophone()->boundary != Am::Allophone::isFinalPhone));
Yeah that's true, you need to cast to boolean as an in-between step. I think the simplest would be
`u32 weClass = !!(a.allophone()->boundary & Am::Allophone::isFinalPhone);`.

2022-11-22 14:07 UTC, Marvin84 commented on src/Am/ClassicStateTying.cc
> +                        (a.allophone()->boundary != Am::Allophone::isFinalPhone));
But then this is also a two-step operation, not so much simpler. If you agree, I would just stick to what is here which is probably more readable for a user who does not know how each boundary class is implemented. What is your take?

2022-11-25 09:44 UTC, NeoLegends reviewed
The state tying impl looks good to me, I just left very minor nits.

Maybe this is not the right place to discuss this, but generally I wonder if we can improve on the `useBoundaryClasses` / `useWordEndClasses` approach. Currently we use two separate booleans, so we have four possible combinations of `true/false`, but only three valid combinations. This sounds more like a use case for an enum with three states to me.

Maybe this ship has already sailed because we'd need to adapt so much code elsewhere, but what would you think about a `use-word-end-boundary-classes` config parameter that can take the values `none` / `word-end` / `boundary` instead of the two boolean flags (in a follow up PR maybe)?

2022-11-25 09:44 UTC, NeoLegends commented on src/Am/ClassicStateTying.cc
> +    require(!(useBoundaryClasses_ &&  useWordEndClasses_));
Nit:
```suggestion
    require(!(useBoundaryClasses_ && useWordEndClasses_));
```

2022-11-25 09:44 UTC, NeoLegends commented on src/Am/ClassicStateTying.cc
> +    require(!(useBoundaryClasses_ &&  useWordEndClasses_));
```suggestion
    require(!(useBoundaryClasses_ && useWordEndClasses_));
```

2022-11-25 09:44 UTC, NeoLegends approved these changes

2022-11-25 12:35 UTC, Marvin84 commented
> This sounds more like a use case for an enum with three states to me.

Good point, I agree. The only problem is that there might be legacy setups that will break due to hash changes on sisyphus side. However, since still few people are using the dense tying, we might still be on time to do this change. Let's see what @curufinwe and @SimBe195 think about this.

2022-11-25 13:06 UTC, NeoLegends commented
> [ADD] I can anyhow guarantee one rasr version under a separate branch that has still the old behavior for such cases.

Perhaps this is a case where we should make RASR backwards compatible, so that it supports both ways of setting the WE/BD class configuration (in one branch, seems easy enough). Internally RASR would use the three-state enum, but externally (in the CRP) it can be configured both ways as long as the user choses one variant or the other.

This way we can keep the hashes of existing setups and we're less error prone inside of RASR.

2022-11-29 10:26 UTC, SimBe195 commented
If, like you said, (almost) no one uses these tyings so far I would be fine with losing the backwards compatibility here. The renaming of `"diphone-no-tying-dense"` is anyway also a change that breaks old setups. Ideal would be either a 3- (or 4-)-state enum or two boolean flags like `"use-word-end-classes"` and `"use-word-begin-classes"` which are not mutually exclusive. If both of these flags are true this would be equivalent to the `"use-boundary-classes"` flag that we have now.

2022-11-29 11:07 UTC, curufinwe requested changes
Only one minor thing.

2022-11-29 11:07 UTC, curufinwe commented on src/Am/ClassicStateTying.cc
> +        u32 weClass = a.allophone()->boundary & Am::Allophone::isFinalPhone ? 1 : 0;
I would add brackets around the check. s.t. it's unambiguous (for those who don't know operator precedence by heart) that the `&` is evaluated before the `?`

2022-11-29 11:07 UTC, curufinwe commented on src/Am/ClassicStateTying.cc
> +        u32 weClass = a.allophone()->boundary & Am::Allophone::isFinalPhone ? 1 : 0;
see above

2022-11-29 18:09 UTC, curufinwe approved these changes

2022-11-29 18:11 UTC, merged