Generic Seq2Seq Decoder
rwth-i6/rasr pull request #44
Opened 2023-02-15 16:53 UTC by ZhouW321

check changes on Tensorflow first

2023-02-16 15:46 UTC, curufinwe requested changes

2023-02-17 10:13 UTC, ZhouW321 commented on src/Tensorflow/Tensor.cc
> +        // code simplicity instead of efficiency here (anyway very rarely used)
the efficiency difference is tested to be there. This is not about offsets cached, but yes, about the extra addition executed for each element of each Tensor in each batch   * numHiddenVar. Depending on search space size, the impact can vary. I'd rather keep it as this is the most frequent usage of hidden states.

2023-02-17 10:17 UTC, ZhouW321 commented on src/Tensorflow/Tensor.cc
> +        std::vector<int64> shape({inputs[0]->dimSize(0), inputs[0]->dimSize(1),
how to do the element-wise assign which requiring explicit for loops over all ranks ?

2023-02-17 10:19 UTC, ZhouW321 commented on src/Tensorflow/Tensor.cc
> +    require(1 <= nDim && nDim <= 3); // higher rank not supported here
ok

2023-02-17 10:48 UTC, ZhouW321 commented on src/Tensorflow/Tensor.hh
> +    static Tensor concatN(const std::vector<const Tensor*>& inputs, int axis);
ok

2023-02-17 11:06 UTC, ZhouW321 commented on src/Tensorflow/Tensor.hh
> +    static Tensor concatN(const std::vector<const Tensor*>& inputs, int axis);
ok

2023-02-17 12:22 UTC, ZhouW321 commented on src/Tensorflow/Tensor.cc
> +                require_eq(size1, input->dimSize(1));
this is also for small efficiency gain for the most frequent usage, to avoid  evaluation of the same condition in many loop iterations (~ numHiddenVars * search space size)

2023-02-17 18:05 UTC, ZhouW321 commented
ok, simplicity and efficiency should be both kept.

2023-02-20 11:59 UTC, curufinwe commented on src/Tensorflow/Tensor.hh
> +        tensor_.reset(new tf::Tensor(*other.tensor_));
```suggestion
    if (other.empty()) {
        tensor_.release();
    }
    else {
        tensor_.reset(new tf::Tensor(*other.tensor_));
    }
```

2023-02-20 12:00 UTC, curufinwe commented on src/Tensorflow/Tensor.cc
> +        std::vector<int64> shape({inputs[0]->dimSize(0), inputs[0]->dimSize(1),
yes

2023-02-20 12:01 UTC, curufinwe approved these changes

2023-02-20 12:05 UTC, SimBe195 approved these changes

2023-02-20 12:05 UTC, merged