feat: Allow 24-bit acoustic model indices
rwth-i6/rasr pull request #52
Opened 2023-04-25 14:02 UTC by NeoLegends

This PR allows for 24-bit acoustic model indices/state indices in the same 32-bit as previously used for the StateDesc struct by using bit fields to make use of the padding in the struct.

2^24 = 16,777,216.

Here is an example (Rust) playground, which demonstrates the size of the struct stays the same: https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=dc00f470e0cfa3272d02b00f96a04e59. The example uses the same layout rules as C/C++ would.

2023-05-03 14:20 UTC, curufinwe requested changes
1. Have you tested if there is a performance impact from this change?
2. Please at least update the DiskFormatVersion inside TreeStructure.cc, better update the code to also load the previous version. In any case have a test-setup where you make sure that RASR behaves well with an old global-cache.

2023-05-03 15:03 UTC, Marvin84 commented
@NeoLegends  I agree with @curufinwe that this needs to be first tested. I add also @SimBe195 for his input.
My understanding is that there are different function calls that now need to read properly the acoustic and transition indices and the mere change of the struct as in this PR might not be enough.

2023-06-02 16:59 UTC, curufinwe requested changes

2023-06-02 16:59 UTC, curufinwe commented on src/Search/StateTree.cc
> +const StateTree::StateDesc::ModelIndex StateTree::invalidAcousticModel = Core::Type<StateTree::StateDesc::ModelIndex>::max;
I'm not sure if this is correct here. Some states might store invalidAcousticModel in the state-tree and the value here is 2^32 - 1, but the maximum value that can be read from StateDesc::acousticModel is 2^24 -  1.

2023-06-02 16:59 UTC, curufinwe commented on src/Search/StateTreeIo.cc
> +    read(i, am);
I think it's better to store the data as one 32-bit value and then write the upper 8 bit into transitionModel index and the lower 24 bits into acousticModel

2023-06-02 16:59 UTC, curufinwe commented on src/Search/StateTreeIo.cc
> +    write(o, am);
This also needs to be changed then (see above).

2023-06-02 16:59 UTC, curufinwe commented on src/Search/StateTreeIo.cc
> +const int         StateTreeIo::fileFormatVersion = 6;
Is this checked anywhere? If so adding backwards compatibility would be nice.

2023-08-23 08:43 UTC, curufinwe commented on src/Search/StateTree.cc
> +    if (acousticModel_->nStateTransitions() >= StateDesc::MAX_AM) {
This is incorrect, the maximum number of transition models is much lower than the maximum number of acoustic models. This should be `Core::Type<StateDesc::TransitionModelIndex>::max`

2023-08-24 12:00 UTC, curufinwe commented
I have tested your implementation by merging it into the AppTek-rasr codebase and running some of our models with it. I fixed the bugs that I found and think that now it's ready to be merged.

2023-08-24 12:00 UTC, curufinwe approved these changes

2023-09-07 10:15 UTC, merged

2023-09-07 10:16 UTC, NeoLegends commented
🎉