Add python bindings
rwth-i6/rasr pull request #69
Opened 2023-11-10 13:10 UTC by DanEnergetics

- Add LibRASR shared library
- Make a pip installable package
- RASR features available in Python module:
  - create Configuration object and read a RASR config file from disk
  - Pass configuration to AllophoneStateFsaBuilder to build weighted Automata
- Let Core::Configuration class have Core::Ref pointer to ResourceDataBase object

2023-11-24 17:44 UTC, curufinwe requested changes
We also need the following changes to the recently merged apptainer image:
```
diff --git a/apptainer/2023-11-08_tensorflow-2.14_v1/image.def b/apptainer/2023-11-08_tensorflow-2.14_v1/image.def
index 1ad19d7..6138f0c 100644
--- a/apptainer/2023-11-08_tensorflow-2.14_v1/image.def
+++ b/apptainer/2023-11-08_tensorflow-2.14_v1/image.def
@@ -10,6 +10,8 @@ Stage: build
         bison libxml2-dev libopenblas-dev libsndfile1-dev libcrypto++-dev libcppunit-dev \
         parallel xmlstarlet python3-lxml htop strace gdb sox python3-pip cmake ffmpeg vim
 
+    pip3 install pybind11==2.11.1
+
     # download the cache manager and place in /usr/local
     cd /usr/local
     git clone https://github.com/rwth-i6/cache-manager.git
diff --git a/apptainer/2023-11-08_tensorflow-2.14_v1/makefiles/config/os-linux.make b/apptainer/2023-11-08_tensorflow-2.14_v1/makefiles/config/os-linux.make
index cd7549d..a0a150d 100644
--- a/apptainer/2023-11-08_tensorflow-2.14_v1/makefiles/config/os-linux.make
+++ b/apptainer/2023-11-08_tensorflow-2.14_v1/makefiles/config/os-linux.make
@@ -144,6 +144,8 @@ LDFLAGS     += `${PYTHON_PATH}/bin/python3.11-config --ldflags --embed 2>/dev/nu
 LDFLAGS     += -Wl,-rpath -Wl,${PYTHON_PATH}/lib
 else
 INCLUDES    += `python3.11-config --includes 2>/dev/null`
+INCLUDES    += -I$(shell python3.11 -c 'import numpy as np; print(np.get_include())')
+INCLUDES    += `python3.11 -m pybind11 --includes 2>/dev/null`
 LDFLAGS     += `python3.11-config --ldflags --embed 2>/dev/null`
 # IF you want to use Python2 for whatever reason:
 # INCLUDES    += `pkg-config --cflags python`
```

2023-11-24 17:44 UTC, curufinwe commented on src/Python/Makefile
>  LIBPYTHON_O    = \
You need to add
```
ifdef MODULE_TENSORFLOW
CXXFLAGS += $(TF_CXXFLAGS)
LDFLAGS  += $(TF_LDFLAGS)
endif
```
to the Makefile (ideally after CCFLAGS)

2024-05-15 15:54 UTC, curufinwe requested changes
Some last changes. Please also talk to @NurAd-Din and/or @hannah220 .

2024-05-15 15:54 UTC, curufinwe commented on src/Python/PybindModule.cc
> +#ifdef MODULE_STREAMING
This module is not part of github RASR -> remove

2024-05-15 15:54 UTC, curufinwe commented on src/Python/PybindModule.cc
> +class _DummyApplication : Core::Application {
After some thought, I think it would be best to merge this class with it's duplicate in Tools/LibRASR and also move the PYBIND11_MODULE into Tools/LibRasr

2024-05-29 14:41 UTC, DanEnergetics commented
I'm wondering if we want to be able to `make` with calling `pip install .` instead of or as an additional alternative to making it manually beforehand. This is possible with some setuptools magic.

2024-05-29 15:43 UTC, JackTemaki commented
> I'm wondering if we want to be able to `make` with calling `pip install .` instead of or as an additional alternative to making it manually beforehand. This is possible with some setuptools magic.

Something like here: https://github.com/flashlight/text/blob/main/setup.py would definitely be nice... The question is how much overhead this is to be stable and working in most cases.

2024-05-29 17:31 UTC, DanEnergetics commented
Yes that's what I was thinking about. I tried a similar implementation using the existing make system and it seems to work. The only thing is that we might want to pass arguments to the `pip install .` call in order to call `configure --i6 --disable-modules=...` or something like that.

2024-06-21 11:58 UTC, curufinwe approved these changes

2024-06-25 13:19 UTC, JackTemaki commented
```
/usr/bin/ld: ../../Python/libSprintPython.linux-x86_64-standard.a(AllophoneStateFsaBuilder.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZZN8pybind116handle15inc_ref_counterEmE7counter' can not be used when making a shared object
```

2024-06-25 14:30 UTC, JackTemaki commented
I can compile it with my image after some fixes (which are unrelated to this PR), run setuptools and access the package in IPython. I will do some testing together with @Marvin84 tomorrow.

2024-06-27 13:44 UTC, JackTemaki approved these changes
Can confirm that it works. There are some improvements possible but I guess this can all be future work.

2024-06-27 13:56 UTC, JackTemaki commented
@curufinwe as there is some extra code needed to convert from the FSA here to the FSA needed for fast baum welch? Is there already a plan to put this code somewhere? E.g. to i6_models? I am talking about something like this, which I found in Daniels setup:
```python
    def build_batch(self, seq_tags):
        def concat_fsas(a: Tuple, b: Tuple):
            edges = torch.from_numpy(np.int32(b[2])).reshape((3, b[1]))
            return (
                a[0] + [b[0]], # num states
                a[1] + [b[1]], # num edges
                torch.hstack([a[2], edges]), # edges
                torch.cat([a[3], torch.from_numpy(b[3])]), # weights
            )
        fsas = map(self.builder.build_by_segment_name, seq_tags)
        num_states, num_edges, all_edges, all_weights = reduce(
            concat_fsas, fsas, ([], [], torch.empty((3, 0), dtype=torch.int32), torch.empty((0,)))
        )
        num_edges = torch.tensor(num_edges, dtype=torch.int32)
        num_states = torch.tensor(num_states, dtype=torch.int32)

        cum_num_states = torch.cumsum(num_states, dim=0, dtype=torch.int32)
        state_offsets = torch.cat([torch.zeros((1,), dtype=torch.int32), cum_num_states[:-1]])
        start_end_states = torch.vstack([state_offsets, cum_num_states - 1])

        edge_seq_idxs = torch.repeat_interleave(num_edges)
        all_edges[:2,:] += torch.repeat_interleave(state_offsets, num_edges)
        all_edges = torch.vstack([all_edges, edge_seq_idxs])

        if self.tdp_scale != 1.0:
            all_weights *= self.tdp_scale

        return (
            cum_num_states[-1],
            all_edges.to(cuda_device),
            all_weights.to(cuda_device),
            start_end_states.to(cuda_device)
        )
    ```

2024-06-27 16:10 UTC, DanEnergetics commented
> is there already a plan to put this code somewhere? E.g. to i6_models? [...]
There is an updated version of this being pushed to the AppTek recipes. I discussed this shortly with @michelwi, who suggested to put it under i6_experiments. I'm also leaning towards i6_models

2024-07-02 09:46 UTC, merged