Basic text lexicon parser
rwth-i6/rasr pull request #77
Opened 2024-10-29 12:32 UTC by larissakl

Support for simple text lexica instead of XML-files.
This is meant for unconstrained search for which the XML-format is unnecessarily complicated.
Instead of an XML-lexicon, one can use a txt-file containing one label per line.
For example
```
A
B
C
```
will be parsed to a Bliss Lexicon equivalent to 
```
<?xml version="1.0" ?>
<lexicon>
  <phoneme-inventory>
    <phoneme>
      <symbol>A</symbol>
      <variation>none</variation>
    </phoneme>
    <phoneme>
      <symbol>B</symbol>
      <variation>none</variation>
    </phoneme>
    <phoneme>
      <symbol>C</symbol>
      <variation>none</variation>
    </phoneme>
    <phoneme>
 </phoneme-inventory>
  <lemma>
    <orth>A</orth>
    <phon>A</phon>
  </lemma>
  <lemma>
    <orth>B</orth>
    <phon>B</phon>
  </lemma>
  <lemma>
    <orth>C</orth>
    <phon>C</phon>
  </lemma>
</lexicon>
```

2024-10-29 14:10 UTC, SimBe195 requested changes

2024-10-29 14:10 UTC, SimBe195 commented on src/Bliss/LexiconParser.hh
>      typedef Core::XmlSchemaParser Precursor;
Avoid the `Precursor` definition with multiple inheritance like this since it's not clear later which parent class `Precursor` refers to later without checking back.

2024-10-29 14:10 UTC, SimBe195 commented on src/Bliss/LexiconParser.cc
> +    }
```suggestion
    if (phonemeInventory_->phoneme(symbol)) {
        return;
    }
```

2024-10-29 14:10 UTC, SimBe195 commented on src/Bliss/LexiconParser.cc
> +    currentPhoneme_->setContextDependent(false);
```suggestion
    Phoneme* newPhoneme_ = phonemeInventory_->newPhoneme();
    // set symbol
    phonemeInventory_->assignSymbol(newPhoneme_, symbol);
    // set variation to none
    newPhoneme_->setContextDependent(false);
```

2024-10-29 14:10 UTC, SimBe195 commented on src/Bliss/LexiconParser.cc
> +    }
```suggestion
    if (lexicon_->lemma(symbol)) {
        return;
    }
```

2024-10-29 14:10 UTC, SimBe195 commented on src/Bliss/LexiconParser.cc
> +    lexicon_->setDefaultLemmaName(currentLemma_);
```suggestion
    Lemma* newLemma_ = lexicon_->newLemma();
    // set orth
    lexicon_->setOrthographicForms(newLemma_, {symbol});
    // set phon
    Pronunciation* pron = lexicon_->getPronunciation(symbol);
    lexicon_->addPronunciation(newLemma_, pron);
    lexicon_->setDefaultLemmaName(newLemma_);
```

2024-10-29 14:10 UTC, SimBe195 commented on src/Bliss/LexiconParser.hh
> +    virtual int parseFile(const std::string& filename) = 0;
I'm not sure why `parseFile` is supposed to return an `int` even though the return value is only ever used as a boolean, right? Since you are touching the code anyway, I would convert the return type to `bool`.

2024-10-29 14:21 UTC, larissakl commented on src/Bliss/LexiconParser.cc
> +    // second pass: create the lemmata in the lexicon
I think this is not directly possible. The phoneme inventory needs to be set before pronunciation for a lemma can be set because `Lexicon::getPronunciation()` requires the phoneme inventory.
 Instead, we could pass the file once, set the phonemes and collect the labels as string in a vector and then do another pass over this vector to set the lemmata. This also requires two passes, but only one pass over the file. What do you think?

2024-10-29 14:40 UTC, larissakl commented on src/Bliss/LexiconParser.hh
>      typedef Core::XmlSchemaParser Precursor;
This was left from the original code and I tried to avoid touching that... So in the constructor, I can just use `XmlSchemaParser(c)` instead of `Precursor(c)`, right?

2024-10-29 15:24 UTC, SimBe195 commented on src/Bliss/Lexicon.cc
> +    if (filename.compare(filename.length()-4, 4, ".txt") == 0)
Right, that's what I meant. You can search for instances of `ParameterChoice` in other places in the RASR code to see how this is done.

2024-10-29 15:24 UTC, SimBe195 commented on src/Bliss/LexiconParser.cc
> +    // second pass: create the lemmata in the lexicon
You also don't need a vector I believe. The `PhonemeInventory` class provides a function `phonemes()` which returns a pair of iterators that you can use for the second pass.

2024-10-29 15:24 UTC, SimBe195 commented on src/Bliss/LexiconParser.hh
>      typedef Core::XmlSchemaParser Precursor;
Originally `XmlSchemaParser` was also the only parent but now `Precursor` is ambiguous.

2024-10-29 15:35 UTC, larissakl commented on src/Bliss/LexiconParser.cc
> +    // second pass: create the lemmata in the lexicon
Ah yes, good idea. Then I will change the `createLemma()` method such that it iterates over the phonemes and creates the lemmata and call it only once in `parseFile()`.

2024-10-29 20:10 UTC, larissakl commented on src/Bliss/LexiconParser.hh
>      typedef Core::XmlSchemaParser Precursor;
Please let me know if this is correct now

2024-10-30 08:41 UTC, SimBe195 requested changes

2024-10-30 08:41 UTC, SimBe195 commented on src/Bliss/Lexicon.cc
> +        "text", txtLexicon,
Maybe call it a different name like `vocab-txt` or something so that the type suggests that this is just a file with a list of labels. If it's called `txt` and later someone wants to build a full text-based pronunciation lexicon parser the naming will become difficult/confusing. Such a name change could also be applied to the class names.

2024-10-30 08:41 UTC, SimBe195 commented on src/Bliss/Lexicon.cc
> +        "type", &Lexicon::lexiconTypeChoice, "type of the lexicon file", xmlLexicon);
```suggestion
const Core::ParameterChoice Lexicon::paramLexiconType(
        "type", &Lexicon::lexiconTypeChoice, "type of the lexicon file", xmlLexicon);
```

2024-10-30 08:41 UTC, SimBe195 commented on src/Bliss/Lexicon.cc
> +    switch (Lexicon::LexiconType(lexType)) {
```suggestion
    switch (paramLexiconType(config)) {
```

2024-10-30 08:41 UTC, SimBe195 commented on src/Bliss/Lexicon.cc
> +    case Lexicon::LexiconType::txtLexicon:
```suggestion
    case LexiconType::txtLexicon:
```

2024-10-30 08:41 UTC, SimBe195 commented on src/Bliss/Lexicon.cc
> +    case Lexicon::LexiconType::xmlLexicon:
```suggestion
    case LexiconType::xmlLexicon:
```

2024-10-30 08:41 UTC, SimBe195 commented on src/Bliss/Lexicon.cc
>          error("Error while reading lexicon file.");
```suggestion
    if (!parser->parseFile(filename)) {
        error("Error while reading lexicon file.");
    }
```

2024-10-30 08:41 UTC, SimBe195 commented on src/Bliss/LexiconParser.cc
> +void TextLexiconParser::createPhoneme(const std::string line) {
```suggestion
void TextLexiconParser::createPhoneme(const std::string& line) {
```

2024-10-30 09:26 UTC, merged