Add Core::CollapsedVector
rwth-i6/rasr pull request #78
Opened 2024-10-31 12:04 UTC by SimBe195

Vector that is automatically collapsed down to one element if all entries have the same value
From the outside it behaves like a normal vector. Whether it is collapsed or not only matters internally.

Example:

```
CollapsedVector<int> v;  // Internal data of v is [] with logical size 0
v.push_back(5);  // Normal push. Internal data of v is [5] with logical size 1
v.push_back(5);  // v stays collapsed. Internal data of v is [5] with logical size 2
std::cout << v.size() << std::endl;  // Prints "2"
std::cout << v[1] << std::endl;  // Prints "5"
v.push_back(6);  // v is expanded because the new value is different. Internal data of v is [5, 5, 6] with logical size 3
std::cout << v[2] << std::endl;  // Prints "6"
v.clear();  // Internal data of v is [] with logical size 0.
```

2024-10-31 12:30 UTC, larissakl commented on src/Core/CollapsedVector.hh
> +    bool     isCollapsed() const;
Is this still needed? It's not implemented below.

2024-10-31 12:31 UTC, larissakl commented on src/Core/CollapsedVector.hh
> +    bool     isCollapsed() const;
Oh sorry, you were faster :)

2024-11-01 19:41 UTC, larissakl approved these changes

2024-11-07 13:54 UTC, Marvin84 approved these changes

2024-11-08 13:45 UTC, curufinwe requested changes
In addition to inline comments, please also add `inline` to the function definitions, s.t. the linker does not treat it as an error if two object files with the same symbol are linked together.

2024-11-08 13:45 UTC, curufinwe commented on src/Core/CollapsedVector.hh
> +    if (data_.empty() or data_.size() > 1ul) {
This can be shortened to `data_.size != 1`

2024-11-08 13:45 UTC, curufinwe commented on src/Core/CollapsedVector.hh
> +    return data_.operator[](idx);
no need to explicitly call `operator[]`, just write `data_[idx]`

2024-11-08 13:45 UTC, curufinwe commented on src/Core/CollapsedVector.hh
> +    return operator[](idx);
Alternative: `(*this)[idx]`. But feel free to also keep your version if you like it better.

2024-12-04 15:51 UTC, SimBe195 commented on src/Core/CollapsedVector.hh
> +    return data_.operator[](idx);
Right, I think this is probably because initially the class inherited from `std::vector` instead of having it as a member so later I replaced all occurrences of `this->` with `data_.`

2025-01-08 13:40 UTC, curufinwe approved these changes

2025-01-08 13:41 UTC, merged