Add Core::FIFOCache
rwth-i6/rasr pull request #79
Opened 2024-10-31 12:25 UTC by SimBe195

Cache based on an unordered_map with a maximum size such that when the cache is full and
a new item is trying to be added, the oldest item in the cache gets removed.
Note: oldest is determined by order of insertion, not order of last access.

Example:
```
FIFOCache<int, std::string> cache(2);  // Cache has room for two items
cache.put(1, "one");  // Internal data: {1: "one"}
cache.put(2, "two");  // Internal data: {1: "one", 2: "two"}
cache.put(3, "three");  // Oldest element is deleted since max size was reached. Internal data: {2: "two", 3: "three"}
```

2024-11-08 13:40 UTC, larissakl approved these changes

2024-11-08 13:56 UTC, curufinwe requested changes

2024-11-08 13:56 UTC, curufinwe commented on src/Core/FIFOCache.hh
> +
superfluous newline

2024-11-08 13:56 UTC, curufinwe commented on src/Core/FIFOCache.hh
> +    return cacheMap_.at(key);
This throws an exception if the key is not present. As nobody ever catches these it will probably terminate the application. I think it would be better to return `std::optional<Value&>` and for an interface the default-constructs the value add an `operator[]` function.

For the version returning `std::optional<Value&>` we could also have a const version of the function.

2024-11-08 17:33 UTC, curufinwe commented
PS: same comment about adding `inline` as in https://github.com/rwth-i6/rasr/pull/78

2024-12-05 09:45 UTC, SimBe195 commented on src/Core/FIFOCache.hh
> +    return cacheMap_.at(key);
C++ unfortunately doesn't support optional references so `std::optional<Value&>` doesn't work . I have implemented this now by using `std::optional<std::reference_wrapper<Value>>`. It could also be done by using `Value*` as return value instead and returning `nullptr` when the key is not found.

2025-01-08 15:08 UTC, curufinwe commented on src/Core/FIFOCache.hh
> +        return std::reference_wrapper<Value>(it->second);
Here the "recommended" way would be to use `std::ref()`: https://en.cppreference.com/w/cpp/utility/functional/ref
Also in the function below.

2025-01-10 17:18 UTC, merged